# Generated by Django 4.0.4 on 2022-05-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_status',
            options={'verbose_name': 'Event Status', 'verbose_name_plural': 'Event Status'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True),
        ),
    ]
